#!/bin/bash

FIND_BASINS=${1-0}
INPUT=${2-aoc.input}

declare -a GRID
SPIN=0
function spin() {
  local spinner="/-\|"
  echo -en "\033[D"
  printf "%s" "${spinner:${SPIN}:1}"
  (( SPIN = (SPIN + 1) % ${#spinner} ))
}

invalid_score=0
SCORES=()
while read line
do
echo test line ${line}
  incomplete_score=0
  BRACE=()
  stop=0
  for (( i = 0; i < ${#line}; i++ )); do
    ch=${line:${i}:1}
    case ${ch} in
      "("|"["|"{"|"<") 
        BRACE+=( ${ch} )
        ;;
      ")") 
        if [ ${BRACE[-1]} != "(" ]; then
          (( invalid_score += 3 ))
          stop=1
          break
        fi
        unset BRACE[-1]
        ;;
      "]") 
        if [ ${BRACE[-1]} != "[" ]; then
          (( invalid_score += 57 ))
          stop=1
          break
        fi
        unset BRACE[-1]
        ;;
      "}") 
        if [ ${BRACE[-1]} != "{" ]; then
          (( invalid_score += 1197 ))
          stop=1
          break
        fi
        unset BRACE[-1]
        ;;
      ">") 
        if [ ${BRACE[-1]} != "<" ]; then
          (( invalid_score += 25137 ))
          stop=1
          break
        fi
        unset BRACE[-1]
        ;;
    esac
  done

echo "finished reading chars; left with ${BRACE[@]}"
  if [ ${stop} -eq 1 ]; then
    continue
  fi
  while [ ${#BRACE} -gt 0 ]; do
    (( score *= 5 ))
    case ${BRACE[-1]} in
      "(")
        (( score += 1 ))
        ;;
      "[")
        (( score += 2 ))
        ;;
      "{")
        (( score += 3 ))
        ;;
      "<") 
        (( score += 4 ))
        ;;
    esac
    unset BRACE[-1]
  done
  SCORES+=( ${score} )
done < "${INPUT}"
echo scores: ${SCORES[@]}
sorted=$( printf '%d\n' ${SCORES[@]} | sort -n | paste -sd, )
echo sorted scores: ${sorted}
IFS=',' read -r -a SCORES <<< ${sorted}
echo sorted scores: ${SCORES[@]}
echo score: ${SCORES[$(( ${#SCORES[@]} / 2))]}

exit 0
value=()
for (( i = 0; i < ${#GRID[@]}; i++ )); do
  for (( j = 0; j < ${#GRID[0]}; j++ )); do
    if [ ${GRID[${i}]:${j}:1} -eq 9 ]; then
      continue
    fi
    if [ ${FIND_BASINS} -eq 0 ]; then
      findLow ${j} ${i}
    else
      getBasinSize ${j} ${i} 0
    fi
    result=$?
    if [ ${result} -gt 0 ]; then
      values+=( ${result} )
    fi
  done
done

echo -ne "\033[1D"
if [ ${FIND_BASINS} -eq 0 ]; then
  printf '%d\n' ${values[@]} | sort -n | paste -sd+ | bc -l
else
  printf '%d\n' ${values[@]} | sort -n | tail -3 | paste -sd\* | bc -l
fi

