#!/bin/bash

INPUT=$1
if [ -z "${INPUT}" ]; then
  INPUT=aoc.input
fi

typeset -A total
while read entry; do
  cnt=0
  while (( cnt < ${#entry} )); do
    digit=${entry:${cnt}:1}
    if [ ${digit} -eq 1 ]; then
      (( total[${cnt}]++ ))
    else
      (( total[${cnt}]-- ))
    fi
    (( cnt++ ))
  done
done < "${INPUT}"

gamma=0
epsilon=0
cnt=0
while (( cnt < ${#total[@]} )); do
  (( gamma = gamma<<1 ))
  (( epsilon = epsilon<<1 ))
  if [ ${total[$cnt]} -gt 0 ]; then
     (( gamma++ ))
  else
     (( epsilon++ ))
  fi
  (( cnt++ ))
done
echo "${gamma} * ${epsilon}" | bc
