#!/bin/bash

DAYS=${1-80}
INPUT=${2-aoc.input}

FISH=( 0 0 0 0 0 0 0 )
NEW_FISH=( 0 0 0 0 0 0 0 0 0 )

function nextDay() {
  local idx
  local prev_idx
  local new_fish=${FISH[0]:-0}
  for (( idx = 1; idx < ${#FISH[@]}; idx++ )); do
    (( prev_idx = idx - 1 ))
    FISH[${prev_idx}]=${FISH[${idx}]}
  done
  (( new_fish += ${NEW_FISH[0]:-0} ))
  for (( idx = 1; idx < ${#NEW_FISH[@]}; idx++ )); do
    (( prev_idx = idx - 1 ))
    NEW_FISH[${prev_idx}]=${NEW_FISH[${idx}]}
  done
  FISH[6]=${new_fish}
  NEW_FISH[8]=${new_fish}
}

function countFish() {
  local cnt
  for fish in ${FISH[@]}; do
    (( cnt += fish ))
  done
  for fish in ${NEW_FISH[@]}; do
    (( cnt += fish ))
  done
  echo ${cnt}
}

IFS=', ' read -r -a array < ${INPUT}
for count in ${array[@]}; do
  if [ -z "${FISH[${count}]}" ]; then
    FISH[${count}]=0
  fi
  (( FISH[${count}]++ ))
done
for (( i = 0; i < ${DAYS}; i++ )); do
  nextDay
done
echo -e "\033[D$( countFish )"

